### ISSUE TITLE
urls.py cannot work after fresh install, then Page not found after hot-fix

### ISSUE THREAD

**Issue by jimfang** [pyexcel-webwares/django-excel#46]
Environment: Windows10, Python 3.6, Django 2.0.6
--------------------------------------------------------------------------------
// logs with command: manage.py runserver
'''
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03BED7C8>
Traceback (most recent call last):
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\urls\conf.py", line 17, in include
    urlconf_module, app_name = arg
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\urls\resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\urls\resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\urls\resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files (x86)\Python36-32\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\github\django-excel\mysite\urls.py", line 6, in <module>
    url(r'^admin/', include(admin.site.urls), name='admin'),
  File "C:\Users\Jim Fang\AppData\Roaming\Python\Python36\site-packages\django\urls\conf.py", line 27, in include
    'provide the namespace argument to include() instead.' % len(arg)
django.core.exceptions.ImproperlyConfigured: Passing a 3-tuple to include() is not supported. Pass a 2-tuple containing the list of patterns and app_name, and provide the namespace argument to include() instead.
'''

**Comment by jimfang** [comment]
pip install -U Django
Requirement already up-to-date: Django in c:\users\jim fang\appdata\roaming\python\python36\site-packages (2.0.6)
Requirement not upgraded as not directly required: pytz in c:\users\jim fang\appdata\roaming\python\python36\site-packages (from Django) (2018.4)

**Comment by jimfang** [comment]
`urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls'))
]`


Request Method: | GET
-- | --
http://127.0.0.1:8000/polls

**Comment by jimfang** [comment]
http://127.0.0.1:8000/polls/ works....
need add '/' by the end.
