### ISSUE TITLE
Realy? Object of type UUID is not JSON serializable

### ISSUE THREAD

**Issue by TimurKhan** [pyexcel-webwares/django-excel#72]
```sheet = pe.get_sheet(model=model)```
Error in formatting: TypeError: Object of type UUID is not JSON serializable.

**Comment by chfw** [comment]
True!

```
>>> import uuid
>>> b
UUID('d7aa5367-f4cd-4209-8591-38fc390584d5')
>>> import json
>>> json.dumps({'a': b})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
....
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UUID is not JSON serializable

```
